
version: "3.5"

services:
  mediaserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mediaserver
    user: ${PUID}:${PGID}
    environment:
      - RD_TOKEN=${RD_TOKEN}
      - TZ=${TZ:-UTC}
      - PUID=${PUID}
      - PGID=${PGID}
      - JELLYFIN_TOKEN=${JELLYFIN_TOKEN:-}  # Optional, defaults to empty
    volumes:
      - ./config:/config
      - ./data:/data
      - ./cache:/cache
      - ./logs:/logs
      - ./filebot:/data/filebot  # Optional FileBot license and groovy files
    ports:
      - "8096:8096"
      - "8920:8920"
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
